export const uiCopy = {
  pl: {
    nav: {
      calendar: "📅 Kalendarz",
      writeNow: "✍️ Pisz teraz",
      projects: "📁 Projekty / Marki",
      stats: "📊 Statystyki",
      settings: "⚙️ Ustawienia",
    },
    overview: {
      title: "Przegląd dnia",
      subtitle: "Najważniejsze zadania redakcyjne na dziś i ten tydzień.",
      postToday: "Post na dziś",
      openAndFinish: "Otwórz i dokończ",
      todayTodo: "Dziś do zrobienia",
      write: "Pisz",
      finish: "Dokończ",
      thisWeek: "Ten tydzień",
      plannedOfSeven: "z 7 zaplanowanych",
      overdue: "Zaległości",
      writeOrFinish: "Napisz / Dokończ",
      last30Days: "Ostatnie 30 dni",
      published: "Opublikowane",
      onTime: "Na czas",
      overdueCount: "Zaległe",
      aiUsage: "Użycie AI",
      upcoming: "Nadchodzące",
      openFullCalendar: "Otwórz pełny kalendarz",
      noTodayTask: "Brak pozycji na dziś. Wybierz temat i zaplanuj publikację.",
      noUpcoming: "Brak nadchodzących publikacji.",
      noOverdue: "Brak zaległości. Plan jest pod kontrolą.",
    },
    calendarProduct: {
      title: "Kalendarz publikacji",
      subtitle: "Plan tygodnia z szybkim przejściem do pisania.",
      week: "Tydzień",
      month: "Miesiąc",
      channelsLegend: "Kanały",
      channelLinkedin: "LinkedIn",
      channelBlog: "Blog",
      channelInstagram: "Instagram",
      openDay: "Otwórz dzień",
      createDraft: "Utwórz szkic",
      finishDraft: "Dokończ szkic",
      noPublication: "Brak zaplanowanej publikacji",
      alwaysVisible: "Kalendarz jest zawsze dostępny.",
    },
    write: {
      title: "Pisz teraz",
      subtitle: "Skup się na treści — temat, szkic i publikacja w jednym miejscu.",
      channel: "Kanał",
      topic: "Temat",
      topicPlaceholder: "Wpisz temat publikacji",
      keywords: "Słowa kluczowe",
      keywordsHint: "Wpisz słowa kluczowe po przecinku",
      generateFullPost: "Generuj cały post",
      writeIntro: "Napisz wstęp",
      suggestCta: "Zaproponuj CTA",
      shorten: "Skróć",
      improveTone: "Popraw ton",
      editor: "Edytor treści",
      editorPlaceholder: "Wpisz lub wygeneruj treść publikacji...",
      chars: "Liczba znaków",
      internalLinks: "Linkowanie wewnętrzne",
      externalLinks: "Linkowanie zewnętrzne",
      publishDate: "Data publikacji",
      publishTime: "Godzina publikacji",
      schedule: "Zaplanuj",
      saveDraft: "Zapisz szkic",
      brandContext: "Kontekst marki",
      audience: "Grupa docelowa",
      tone: "Ton komunikacji",
      hashtags: "Hashtagi",
      publishBlockedApproval: "Publikacja wymaga wcześniejszej akceptacji.",
      sendForApproval: "Wyślij do akceptacji",
      aiBlocked: "Generowanie AI jest obecnie zablokowane.",
      latestDrafts: "Ostatnie szkice",
      noDrafts: "Brak szkiców. Utwórz pierwszą treść.",
    },
    projectsProduct: {
      title: "Projekty / Marki",
      subtitle: "Wypełniasz raz — AI zawsze ma kontekst.",
      createProject: "Nowy projekt",
      active: "Aktywny",
      openProjectSettings: "Otwórz ustawienia projektu",
      setAsActive: "Ustaw jako aktywny",
      contextReady: "Kontekst gotowy",
      contextToComplete: "Kontekst wymaga uzupełnienia",
      fields: "Pola kontekstu",
      channels: "Kanały",
      schedule: "Harmonogram",
      noProjects: "Brak projektów. Utwórz pierwszy projekt, aby rozpocząć pracę.",
    },
    statsProduct: {
      title: "Statystyki",
      subtitle: "Wyniki publikacji i konsekwencja zespołu.",
      published: "Opublikowane",
      drafts: "Szkice",
      onTime: "Na czas",
      overdue: "Zaległe",
      byChannel: "Publikacje według kanału",
      weeklyConsistency: "Konsekwencja tygodniowa",
      thisWeek: "Ten tydzień",
      noData: "Brak danych do prezentacji.",
    },
    settingsProduct: {
      title: "Ustawienia",
      projectSettings: "Ustawienia projektu",
    },
    navigation: {
      content: "Treści",
      calendar: "Kalendarz",
      projects: "Projekty",
      planCoverage: "Pokrycie planu",
      settings: "Ustawienia",
      switch: "Przełącz",
      logout: "Wyloguj",
      myAccount: "Moje konto",
    },
    contentReadiness: {
      title: "Gotowość projektu",
      score: "Wynik",
      stateIncomplete: "Niekompletny",
      audience: "Grupa docelowa",
      channels: "Kanały publikacji",
      externalLinks: "Linki zewnętrzne",
      goals: "Cele projektu",
      internalLinks: "Linki wewnętrzne",
      primaryKeywords: "Słowa kluczowe główne",
      secondaryKeywords: "Słowa kluczowe dodatkowe",
      projectName: "Nazwa projektu",
      projectSummary: "Opis projektu",
      toneOfVoice: "Ton komunikacji",
    },
    templates: {
      title: "Szablony",
      blogFirst: "Marketing treści — Blog jako fundament",
      founderBrand: "Marka osobista — publikacje eksperckie jako kanał główny",
      applyTemplate: "Zastosuj szablon",
    },
    limits: {
      upgradePlan: "Zwiększ plan",
      limitReached: "Osiągnięto limit",
      aiDisabled: "AI wyłączone w projekcie",
      monthlyLimitReached: "Osiągnięto miesięczny limit",
      planAndLimits: "Plan i limity",
      blocked: "Zablokowane",
      available: "Dostępne",
      blocksAndReasons: "Blokady i powody",
      currentPlan: "Aktualny plan",
      limits: "Limity",
      usage: "Wykorzystanie",
      seats: "Miejsca",
      aiPerMonth: "AI / mies.",
      pdfPerMonth: "PDF / mies.",
      reachedAiMonthly: "Osiągnięto miesięczny limit AI.",
      reachedPdfMonthly: "Osiągnięto miesięczny limit eksportów PDF.",
      pdfNotInPlan: "Eksport PDF niedostępny w aktualnym planie.",
      aiDisabledByPolicy: "AI wyłączone polityką projektu.",
      noBlock: "Brak blokady.",
    },
    approval: {
      pending: "Oczekuje na akceptację",
      approved: "Zatwierdzone",
      rejected: "Odrzucone",
      notRequired: "Akceptacja niewymagana",
      requestApproval: "Wyślij do akceptacji",
      approve: "Zatwierdź",
      reject: "Odrzuć",
      status: "Status akceptacji",
      requestedBy: "Wnioskujący",
      decidedBy: "Decydujący",
    },
    common: {
      save: "Zapisz",
      cancel: "Anuluj",
      delete: "Usuń",
      edit: "Edytuj",
      status: "Status",
      searchPlaceholder: "Wyszukaj (wkrótce)",
      open: "Otwórz",
      close: "Zamknij",
      create: "Utwórz",
      createContent: "Utwórz treść",
      generateDraft: "Wygeneruj szkic",
      queue: "Do kolejki",
      publish: "Publikuj",
      unknown: "Nieznany",
      planned: "Zaplanowane",
      queued: "W kolejce",
      drafted: "Szkic",
      published: "Opublikowane",
      skipped: "Pominięte",
      archived: "Archiwum",
      ready: "Gotowe",
      toDo: "Do wykonania",
      yes: "Tak",
      no: "Nie",
      missing: "Brak",
    },
    content: {
      title: "Treści",
      subtitle: "Twoje zadania na dziś i plan na tydzień — bez chaosu i zbędnej złożoności.",
      quickActions: "Szybkie akcje",
      autopilot: "Autopilot treści",
      library: "Biblioteka",
      startHere: "Rozpocznij tutaj",
      setupSubtitle: "Zrealizuj kolejne kroki metodycznie i bez chaosu.",
      openProject: "Otwórz projekt",
      generatePlan: "Generuj plan",
      openCalendar: "Otwórz kalendarz",
      generateWeeklyPack: "Wygeneruj paczkę tygodnia",
      choosePlanInCalendar: "Wybierz plan w Kalendarzu",
      governanceApprovalRequired: "Governance: publikacja wymaga zatwierdzenia (status akceptacji = zatwierdzone).",
      restrictedForCoo: "Dostęp ograniczony. Ta sekcja jest dostępna wyłącznie dla roli COO.",
      noTasksInView: "Brak zadań w tym widoku.",
      noContentInFilter: "Brak treści do wyświetlenia w tym filtrze.",
      publicationBlockedByApproval: "Publikacja zablokowana. Najpierw wyślij do akceptacji i uzyskaj status „Zatwierdzone”.",
      openApprovalDrawer: "Otwórz panel akceptacji",
      newContent: "Nowa treść",
      choosePublicationForApproval: "Wybierz publikację z biblioteki i użyj „Otwórz panel akceptacji”.",
      roleLabel: "Twoja rola",
      activeProject: "Aktywny projekt",
      projectReady: "Gotowy do treści",
      completeData: "Uzupełnij dane",
      editProjectContext: "Edytuj kontekst projektu",
      switchProject: "Zmień projekt",
      updateLabel: "Aktualizacja",
      package: "Paczka",
      qualityOk: "Jakość poprawna",
      toImprove: "Do poprawy",
      createNewManually: "Utwórz nową treść ręcznie",
      planCoverageView: "Zobacz pokrycie planu",
      selected: "Wybrane",
      all: "Wszystkie",
      today: "Dziś",
      week: "Tydzień",
      overdue: "Zaległe",
      missingPublicationId: "Brak identyfikatora publikacji",
      sentForApproval: "Wysłano do akceptacji",
      noDecisionPermission: "Brak uprawnień do decyzji",
      invalidDecision: "Niepoprawna decyzja",
      decisionSaved: "Zapisano decyzję",
      publicationBlockedApprovalRequired: "Publikacja zablokowana: wymagana akceptacja",
      aiBlockedPrefix: "AI zablokowane",
      pdfBlockedPrefix: "Eksport PDF zablokowany",
      noActiveProject: "Brak aktywnego projektu",
      noProjectDescription: "Brak opisu projektu.",
      noKeywords: "Brak słów kluczowych.",
      noInternalLinks: "Brak linków wewnętrznych.",
      noExternalLinks: "Brak linków zewnętrznych.",
      completeFields: "Uzupełnij",
      approval: "Akceptacja",
      requestedAt: "Data zgłoszenia",
      metadata: "Metadane polityk",
      auditLite: "Audyt (Lite)",
      noPolicyAuditEntries: "Brak wpisów audytu polityk.",
      showMore: "Pokaż więcej",
      hide: "Ukryj",
    },
    plans: {
      starter: "Plan podstawowy",
      growth: "Plan rozwojowy",
      controlTower: "Plan operacyjny",
      enterprise: "Plan korporacyjny",
      starterDesc: "Plan bazowy dla małych zespołów.",
      growthDesc: "Skalowanie operacji treści i nadzoru.",
      controlTowerDesc: "Zaawansowany tryb operacyjny dla zespołów treści.",
      enterpriseDesc: "Najwyższy poziom limitów i elastyczności korporacyjnej.",
    },
  },
} as const;
