export const decisionLabCopy = {
  triggerTitle: "Decision Lab",
  triggerHint: "What-if",
  title: "Decision Lab",
  subtitle: "Run scenario simulations in seconds.",
  sectionScenario: "Scenario",
  sectionRun: "Run",
  sectionResults: "Results",
  sectionHistory: "History",
  ready: "Ready",
  notReady: "Not ready",
  run: "Run simulation",
  running: "Running…",
  reset: "Reset",
  copyLink: "Copy link",
  copied: "Link copied.",
  copyFallback: "Clipboard unavailable. Copy manually:",
  runError: "Simulation failed. Please try again.",
  noResults: "Run a scenario to see baseline vs projected deltas.",
  noHistory: "No runs in this session yet.",
  compareMode: "Compare to selected run",
  lastRunPrefix: "Last run at",
  interpretationGood: "This scenario likely improves flow.",
  interpretationMixed: "Mixed result: speed up but risk rises.",
  interpretationWorse: "This scenario worsens throughput; use for stress testing.",
  interpretationNeutral: "This scenario has limited measurable impact.",
} as const;
